CREATE DATABASE Callhub;
USE Callhub;

CREATE TABLE Companies (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  Name VARCHAR(255) NOT NULL,
  ImageUrl VARCHAR(255) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Categories (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  Name VARCHAR(25) NOT NULL,
  Priority INT NOT NULL DEFAULT 1,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Sectors (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  Name VARCHAR(25) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Departments (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  Name VARCHAR(255) NOT NULL,
  CompanyId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Companies(Id),
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Users (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  Name VARCHAR(35) NOT NULL,
  Surname VARCHAR(35) NULL,
  AvatarUrl TEXT NULL,
  Email VARCHAR(125) NOT NULL UNIQUE,
  Priority INTEGER NOT NULL DEFAULT 1,
  Password VARCHAR(255) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
  DepartmentId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Departments(Id),
  SectorId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Sector(Id)
);

CREATE TABLE Calls (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  Title VARCHAR(150) NOT NULL,
  Description TEXT NOT NULL,
  Priority INT NOT NULL,
  ServiceLevel INT NOT NULL DEFAULT 1,
  UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(Id),
  CategoryId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Categories(Id),
  Situation INT NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
  Note INT NULL,
  NoteObservation VARCHAR(255) NULL
);

CREATE TABLE Attachs (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  Name VARCHAR(255) NOT NULL,
  Type VARCHAR(5) NOT NULL,
  Size INT NOT NULL,
  CallId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Calls(Id)
);


/*
 * EXECUTE SEEDS
 */

INSERT INTO Users (
  Name, Surname, [Password], Email
) VALUES (
  'Augusto', 'Pereira', '123456', 'augustohtp8@gmail.com'
);

INSERT INTO Companies (
  Name
) VALUES (
  'MGM Produtos Siderúrgicos'
);

INSERT INTO Departments (
  Name, CompanyId
) VALUES (
  'Vendas', (SELECT TOP 1 Id FROM Companies ORDER BY CreatedAt DESC)
);

INSERT INTO Departments (
  Name, CompanyId
) VALUES (
  'Faturamento', (SELECT TOP 1 Id FROM Companies ORDER BY CreatedAt DESC)
);
